name: Publish GitHub Package

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*'

jobs:
  publish-package:
    if: contains(github.event.head_commit.message, 'publish')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: pnpm
          registry-url: https://registry.npmjs.org/
          scope: "@darkmode-code"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the package
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
